---
abstract: 'Tie interface to Net::DNS'
author:
  - 'Dana M. Diederich <diederich@realms.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-DNS
resources:
  homepage: https://metacpan.org/module/Tie::DNS
  repository: http://github.com/dana/perl-Tie-DNS.git
version: 0.63
