---
abstract: 'Tie interface to Net::DNS'
author:
  - 'Dana M. Diederich <dana@realms.org>'
build_requires:
  English: 0
  File::Spec: 0
  Test: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Perl::Critic::Progressive: 0
  Test::PerlTidy: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-DNS
requires:
  Carp: 0
  Net::DNS: 0
  Socket: 0
  Tie::Cache: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dana/perl-Tie-DNS/issues
  homepage: https://github.com/dana/perl-Tie-DNS
  repository: https://github.com/dana/perl-Tie-DNS.git
version: 1.133260
